version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-v1-{{ checksum "Gemfile.lock" }}
            - ruby-v1
      - run: bundle
      - save_cache:
          key: ruby-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - setup_remote_docker
      - run: bundle exec rspec
